# Generated by Django 5.0.3 on 2024-03-14 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=300)),
                ('line2', models.CharField(max_length=300)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.BigIntegerField()),
                ('email', models.EmailField(max_length=300, null=True)),
                ('account', models.BigIntegerField()),
                ('beneficiary_name', models.CharField(max_length=300)),
                ('status', models.SmallIntegerField(default=1)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
                ('gst', models.CharField(max_length=300)),
                ('pan', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.addresstable')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.contact_details')),
            ],
        ),
    ]
