# Generated by Django 5.0.3 on 2024-03-15 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_addresstable_contact_details_vendortable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortable',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendortable',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendortable',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendortable',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendortable',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
