# Generated by Django 5.0.3 on 2024-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_vendortable_created_by_vendortable_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresstable',
            name='date',
        ),
        migrations.AddField(
            model_name='addresstable',
            name='district',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
